import canonicalLaneMathlib.AdmissibleClass
import MarkovSemigroupsApplicationsDiffusionProcessesLemmaCanonicalLaneLean.TransitionSemigroup
import MarkovSemigroupsApplicationsDiffusionProcessesLemmaCanonicalLaneLean.DiffusionProcess
import MarkovSemigroupsApplicationsDiffusionProcessesLemmaCanonicalLaneLean.KolmogorovBackwardEquation

namespace HautevilleHouse
namespace MarkovSemigroupsApplicationsDiffusionProcessesLemmaCanonicalLaneLean

def MarkovSemigroupsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem markov_semigroups_endgame (A : AdmissibleClass) :
    MarkovSemigroupsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end MarkovSemigroupsApplicationsDiffusionProcessesLemmaCanonicalLaneLean
end HautevilleHouse
